### ISSUE TITLE
TypeError: super() takes at least 1 argument (0 given)

### ISSUE THREAD

**Issue by Jakson2030** [ustayready/CredSniper#25]
I insalled it in Kali iwas getting internal serrver error
i tried to install it in ubuntu on digitalocean After fixing some issues due to missing libraries, I got the final error
@jojo :/home/CredSniper# python credsniper.py --module gmail --twofactor --port 443 --ssl --final google.com --hostname xxxxxx
Traceback (most recent call last):
  File "credsniper.py", line 120, in <module>
    cs = CredSniper()
  File "credsniper.py", line 27, in __init__
    self.prepare_module()
  File "credsniper.py", line 37, in prepare_module
    loader=PackageLoader('credsniper', package),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 224, in __init__
    provider = get_provider(package_name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 431, in get_provider
    __import__(moduleOrReq)
  File "/home/CredSniper/credsniper.py", line 120, in <module>
    cs = CredSniper()
  File "/home/CredSniper/credsniper.py", line 27, in __init__
    self.prepare_module()
  File "/home/CredSniper/credsniper.py", line 41, in prepare_module
    self.module = importlib.import_module(module_path).load(self.enable_2fa)
  File "/home/CredSniper/modules/gmail/gmail.py", line 278, in load
    return GmailModule(enable_2fa)
  File "/home/CredSniper/modules/gmail/gmail.py", line 17, in __init__
    super().__init__(self)

**Comment by DakotaNelson** [comment]
This is most likely a python version problem. Whatever version of python you're running (2 or 3), try the other one and see if that works.

**Comment by Jseg0418** [comment]
BeT

**Comment by Jseg0418** [comment]
> This is most likely a python version problem. Whatever version of python 
.nliqyou're running (2 or 3), try the other one - [ ] # and see if that lll~~
Lplpl. Zz
