### ISSUE TITLE
Install Fails - ValueError: The 'credsniper' package was not installed in a way that PackageLoader understands.

### ISSUE THREAD

**Issue by phydroxide** [ustayready/CredSniper#35]
```sudo ./install.sh
Module to deploy (ex: gmail)? gmail
Final redirect URL: www.<domain>.com
Enable SSL? [Y/n] n
Enable two-factor phishing? [Y/n] Y
Enter hostname for certificates (ex: app.example.com): <domain>
Port to listen on (default: 80/443)? 80

[*] Preparing environment...
[*] SSL Enabled: n
[*] Hostname: <domain>
[*] Two-factor: Y
[*] Loading Module: gmail
[*] Port: 80
[*] Destination URL: <domain>
[*] Starting credsniper w/ flags:  --twofactor --verbose
[*] Adding Let's Encypt repository...
sudo: add-apt-repository: command not found
[*] Updating Apt...
[*] Installing pre-reqs...
[*] Creating & activating virtual environment...
[*] Enabling port binding for Python...
[*] Installing required Python modules...
[*] Creating & installing SSL certificates...
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Cert not yet due for renewal

You have an existing certificate that has exactly the same domains or certificate name you requested and isn't close to expiry.
(ref: /etc/letsencrypt/renewal/<domain>.conf)

What would you like to do?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: Keep the existing certificate for now
2: Renew & replace the certificate (may be subject to CA rate limits)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 2
Renewing an existing certificate for <domain>
IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/<domain>/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/<domain>/privkey.pem
   Your certificate will expire on 2022-09-27. To obtain a new or
   tweaked version of this certificate in the future, simply run
   certbot again. To non-interactively renew *all* of your
   certificates, run "certbot renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le

[*] ###################################################
[*] Successfully installed everything!
[*] To run manually just:
[*]     ~/CredSniper$ source bin/activate
[*]     (CredSniper) ~/CredSniper$ python credsniper.py
[*] ###################################################
[*] Launching CredSniper...
Traceback (most recent call last):
  File "/home/<user>/CredSniper/credsniper.py", line 118, in <module>
    cs = CredSniper()
  File "/home/<user>/CredSniper/credsniper.py", line 25, in __init__
    self.prepare_module()
  File "/home/<user>/CredSniper/credsniper.py", line 35, in prepare_module
    loader=PackageLoader('credsniper', package),
  File "/home/<user>/CredSniper/lib/python3.9/site-packages/jinja2/loaders.py", line 291, in __init__
    import_module(package_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/<user>/CredSniper/credsniper.py", line 118, in <module>
    cs = CredSniper()
  File "/home/<user>/CredSniper/credsniper.py", line 26, in __init__
    self.prepare_api()
  File "/home/<user>/CredSniper/credsniper.py", line 54, in prepare_api
    loader=PackageLoader('credsniper', package),
  File "/home/<user>/CredSniper/lib/python3.9/site-packages/jinja2/loaders.py", line 323, in __init__
    raise ValueError(
ValueError: The 'credsniper' package was not installed in a way that PackageLoader understands.
```

**Comment by KSchmeeds** [comment]
I am experiencing this same error.

**Comment by dueoption** [comment]
Same error for me.
